### ISSUE TITLE
Incorrect handling of `sort` field in schema generation

### ISSUE THREAD

**Issue by atkallie** [django-json-api/django-rest-framework-json-api#1120]
## Description of the Bug Report

I believe that the handling of the `sort` field in the schema generation is currently incorrect. (Please correct me if I'm wrong.)

The custom `AutoSchema` class calls [`self._get_sort_parameters(path, method)`]((https://github.com/django-json-api/django-rest-framework-json-api/blob/085554e28c663d9a336bf7174c58d81925d9d650/rest_framework_json_api/schemas/openapi.py#L425)) for all `GET` & `HEAD` requests:

```python
if method in ["GET", "HEAD"]:
    ...
    parameters += self._get_sort_parameters(path, method)
    ...
```

(_Issue 1_) The JSON:API spec says, "A server **MAY** choose to support requests to sort resource _collections_ according to one or more criteria (“sort fields”)." The way that this is currently handled will naively add the sort query parameter irrespective of whether or not `rest_framework_json_api.filters.OrderingFilter` is enabled. Also, this will add a `sort` query parameter for requests for single resources as well (though I think DRF also does this).

(_Issue 2_) The Django REST Framework's `OrderingFilter` class implements a method for `get_schema_operation_parameters` that will also [add a `sort` query parameter to the schema for the operation](https://github.com/encode/django-rest-framework/blob/0618fa88e1a8c2cf8a2aab29ef6de66b49e5f7ed/rest_framework/filters.py#L322). This leads to duplicate `sort` query parameters listed for the operation.

```python
def get_schema_operation_parameters(self, view):
        return [
            {
                'name': self.ordering_param,
                'required': False,
                'in': 'query',
                'description': force_str(self.ordering_description),
                'schema': {
                    'type': 'string',
                },
            },
        ]
``` 

## Current Workaround

I've currently worked around this by overriding the `OrderingFilter` class:
```python
from rest_framework_json_api.filters import OrderingFilter as DJAOrderingFilter

class OrderingFilter(DJAOrderingFilter):
    def get_schema_operation_parameters(self, view):
        return [{"$ref": "#/components/parameters/sort"}]
```

...and the `AutoSchema` class:
```python
from rest_framework_json_api.schemas.openapi import AutoSchema as DJAAutoSchema

class AutoSchema(DJAAutoSchema):
        def _get_sort_parameters(self, path, method):
            return []
```

...and configuring these in my `REST_FRAMEWORK` config so that the `sort` parameter is conditionally added based on whether or not the `OrderingFilter` is enabled, but still uses the schema provided by this lib. Just thought I'd include this as a potential fix to the problem. However, this patch will still include a `sort` query parameter for requests for single resources (mentioned above).

**Comment by sliverc** [comment]
Thanks for your report. I agree this is a bug. The difference between `OrderingFilter.get_schema_operation_parameters` and `#/components/parameters/sort` is just the description, it seems. Therefore, I am asking myself, is it worth creating our own `OrderingFiltering` class with just another description? I think the easiest way would be to simply remove `_get_sort_parameters` and remove reference `#/components/parameters/sort` to address this issue. What are your thoughts?

**Comment by sliverc** [comment]
1. I fully agree with this point. `_get_sort_parameters` needs to be removed with the scheme definition. Additionally, I would set the `ordering_description` to what we use today in the corresponding scheme definition. Would you be open to work on a PR for this?
2. This point is a bit more tricky. The reason is that simply removing sort parameter from the schema for single resource endpoints actually does not mean that the sort parameter cannot be used on single resource object endpoints. And when it is used, no error is thrown and the query to the database will actually be different. I haven't had time yet to look deeper into this, but I have a feeling that an error needs to be thrown when query param `sort` is used on a single resource object. We have to be careful though in terms of regressions.

I recommend we first tackle point 1 and discuss point 2 more deeply afterward.
