### ISSUE TITLE
How to add links (self, related) to model and its relationships?

### ISSUE THREAD

**Issue by jklapuch** [django-json-api/django-rest-framework-json-api#132]
I figured only self links to main model by adding 'url' to fields in serializer. 
How to add "related" link to it? And how to add all links to model relationships?

Thanks

**Comment by jsenecal** [comment]
[ResourceRelatedField](https://github.com/django-json-api/django-rest-framework-json-api/blob/develop/rest_framework_json_api/relations.py#L12) and [RelationshipView](https://github.com/django-json-api/django-rest-framework-json-api/blob/develop/rest_framework_json_api/views.py#L17) are your friends - for the latter, see https://github.com/django-json-api/django-rest-framework-json-api/blob/develop/example/urls_test.py#L25 for information on how to implement it.

For related views, you will obviously need to setup your own views before referencing them in your ResourceRelatedFields

**Comment by Meph-** [comment]
Thank you,
I used ResourceRelatedField before (without RelationshipView), but my mistake was setting fields 

     "related_link_view_name", 
     "self_link_view_name"

The main problem was in my understanding of self and related links for relationships. I wanted for model "user" and relationship "list":
    
    "self": "/lists/<list_id> 
    "related": "/lists"

instead of /users/user_id/relationships/lists. But it's so right in jsonapi specification and my shape is valid only for included objects

**Comment by jsenecal** [comment]
Glad I could help :+1: - If you'd like to contribute to the documentation with your findings it'd be awesome :)

**Comment by jsenecal** [comment]
Lets keep that open to remind us to document this :)

**Comment by Meph-** [comment]
ok, sorry.

**Comment by jerel** [comment]
Fixed by #194
