### ISSUE TITLE
create new Relation

### ISSUE THREAD

**Issue by stushurik** [django-json-api/django-rest-framework-json-api#196]
For relationships we can use ResourceRelatedField. But this relation is based on PrimaryKeyRelatedField, so it use only pk to resolve relations. What about relationships based on other fields ? Maybe it make sense to create new relation based on the SlugRelatedField.

P.S. I am newbie to django-rest-framework-json-api and jsonapi.

**Comment by leifurhauks** [comment]
Based on the JSON API spec, relationships are represented by resource identifier objects, which identify an object based solely on type and id: http://jsonapi.org/format/#document-resource-object-linkage

While it would not conform to the spec, if you wanted to represent related objects by a slug instead, there is nothing stopping you from simply using the SlugRelatedField from regular DRF, at least in theory (I haven't tried it myself).

On the other hand, if what you want is to use a slug as the "id" in json api for a model (which is valid under the spec), one option is to [make the slug field your model's primary key](https://docs.djangoproject.com/en/1.9/ref/models/fields/#primary-key). While django's default `AutoField` primary key is suitable for most uses, there is nothing wrong with using another field as your primary key (though in general it should be a field that isn't going to change, since you might have foreign keys on other models that reference this field).

Let me know if this addresses your issue.

**Comment by stushurik** [comment]
In my case, pk is AutoField. Also I have unique randomly generated slug field. I don`t want to expose internal id to customer. Cause each instance is belong to some user. So if I use id, the api endpoint can look like /api/items/id. In this case user can insert any integer instead id and get item which doesn`t belong to him. I meant integers are to easy to guess. On the other hand, I want to use id internally.

this is simplified use case, I now that I should use some policy.

**Comment by jsenecal** [comment]
Security by obscurity is never a good option. You should limit what objects ban be accessed in the `get_queryset` method of your viewset.

As for @leifurhauks said, the only valid way to represent the `id` is with whatever the django orm uses as the PK as all the internal mechanisms of django-rest-framework are revolving around that concept.

**Comment by stushurik** [comment]
@leifurhauks @jsenecal okay thank you guys. I will consider to change my model`s pk.

**Comment by jerel** [comment]
If you don't want to expose an integer id (to keep visitors from seeing that you only have 10 customers for example) you may like using a UUIDField instead of the default integer. I use UUIDs as my primary keys most places
