### ISSUE TITLE
The JSON API and EmberJS use dashed attributes by default

### ISSUE THREAD

**Issue by batisteo** [django-json-api/django-rest-framework-json-api#238]
My problem is mainly a documentation issue, you should add `JSON_API_FORMAT_KEYS = 'dasherize'` to the README and the docs.

The JSON API specification and the [EmberJS framework expect dash-cased attributes](https://guides.emberjs.com/v2.5.0/models/customizing-serializers/#toc_json-api-document), but the DRF sends by default the (PEP8) underscored attributes.

Beside mentioning the `JSON_API_FORMAT_KEYS` setting, you may consider using the dashed case by default.

**Comment by jerel** [comment]
The JSON API website _recommends_ dasherized names but it's not part of the official spec: http://jsonapi.org/recommendations/#naming so that's why we left names untouched by default.

As you suggest we could nudge people towards it by added it to the example settings block; would you be interested in opening a pull request? We won't make it the default for sure until the next major version as it would break existing APIs
