### ISSUE TITLE
add a self link to a resource object?

### ISSUE THREAD

**Issue by wryfi** [django-json-api/django-rest-framework-json-api#241]
Is there an easy way to add a self link to a resource object?

**Comment by tpilara** [comment]
I think adding `'url'` to the `fields` on your serializer should generate the self link you're looking for.

**Comment by arielpontes** [comment]
According to the JSONAPI documentation, a GET response on a list of articles should look like this:

```
{
  "links": {
    "self": "http://example.com/articles",
    "next": "http://example.com/articles?page[offset]=2",
    "last": "http://example.com/articles?page[offset]=10"
  },
  "data": [{
    "type": "articles",
    "id": "1",
    "attributes": {
      "title": "JSON API paints my bikeshed!"
    },
    "relationships": {…},
    "links": {
      "self": "http://example.com/articles/1"
    }
  }],
…
}
```
Yet there's no link to self in DRF-json-api's output. I'm surprised this is not the default behavior. And I still haven't found out how to make it work.

**Comment by jerel** [comment]
It works by adding `url` to the `fields` tuple in your serializer. If it doesn't work for you make sure that your serializer is extending `rest_framework_json_api.serializers`. I've added a note to the docs that will be published with the next version.

**Comment by tpilara** [comment]
@jerel Adding `url` to `fields` on the serializer will correctly add the `self` link on each object in the serializer, but is there any easy way to get a `self` link in the top-level links object? The JSON API spec has it in all of their examples, but it's not an explicit requirement of the spec.

I solved this personally for list collections by making a custom paginator that includes the self link. It's been a little while since I looked into this, but I remember finding [this](https://github.com/django-json-api/django-rest-framework-json-api/blob/2994592f315e5472ed32488f6d8aa618f4f3d020/rest_framework_json_api/renderers.py#L476) but I don't recall if I could find an easy place to inject links into data. I think where I've noticed this and not found a solution is getting a top-level links object on RelationshipView responses.

**Comment by jerel** [comment]
@tpilara right, top level link handling could be improved. I originally wrote the simple version that we have now to just pull links from the paginator and it's not as flexible or overridable as I'd like. Perhaps a `self.extract_links` [at the line you linked to](https://github.com/django-json-api/django-rest-framework-json-api/blob/2994592f315e5472ed32488f6d8aa618f4f3d020/rest_framework_json_api/renderers.py#L476) would be a step in the right direction? Maybe we could follow the pattern that we used [for meta](https://github.com/django-json-api/django-rest-framework-json-api/blob/2994592f315e5472ed32488f6d8aa618f4f3d020/rest_framework_json_api/renderers.py#L333-L359) and merge its results with the paginator's results.

**Comment by tpilara** [comment]
@jerel That sounds good, I was thinking about something along the same lines. I've been meaning to see if I could write up a top-level links handler that would function similar to how meta is included in the response. I'll try to take a look at that soon and see if I can get something suitable for a PR.

**Comment by arielpontes** [comment]
OK, I've figured out why the `url` wasn't working for me. I had registered my routes with a custom, plural `base_name` (e.g. `snippets-detail`) instead of the default, singular one (e.g. `snippet-detail`), and then when I tried to include the `url` field I got:

```
ImproperlyConfigured at /snippets
Could not resolve URL for hyperlinked relationship using view name "snippet-detail". You may have failed to include the related model in your API, or incorrectly configured the `lookup_field` attribute on this field.
```
In case somebody has similar trouble, my solutions were:

1. Remove the custom `base_name` and let the router define default view names.
2. Customize the `url` field to respect the custom view names. It would look something like that:

```
class SnippetSerializer(serializers.ModelSerializer):

    url = serializers.HyperlinkedIdentityField(
        view_name='snippets-detail',
        lookup_field='pk'
    )

    class Meta:
        model = Snippet
        fields = (…, 'url')
```
