### ISSUE TITLE
500 errors on the live demo when including relationships

### ISSUE THREAD

**Issue by skqr** [django-json-api/django-rest-framework-json-api#259]
Hi!

I'm checking out some of the features of JSON-API implemented on your library.

I'm using JSON-API particularly for its related resource inclusion and resource field selection features.

I tried including an entry's blog, but got a 500 status back. Same with the author.

http://json-api.jerel.co/entries?include=blog

I noticed the entry resource type is actually "posts"; should it not be "entries"?

Thanks for the amazing work!

**Comment by jerel** [comment]
So, what's happening here is that browsers are not displaying the correct error. If you curl the endpoint you will get a 400 error explaining that `blog` or `author` is not supported (`authors` is, it's a has many relationship). To make `blog` available for inclusion you would need to add `'blog': 'example.serializers.BlogSerializer'` to the `included_serializers` attribute on the `example.serializers.EntrySerializer` serializer.

"posts" is manually set just to show off the capability of having a resource `type` overridden instead of the default of "entries".

Hope this helps, if not let us know.
