### ISSUE TITLE
File upload and validation?

### ISSUE THREAD

**Issue by riklaunim** [django-json-api/django-rest-framework-json-api#271]
Is there a supported way of handling file uploads? I've noticed that a file/image field will serialize to an URL to an existing file, but when sending data back in an update will not validate as string with the url is... not a valid file / image :)

Temporarily I have a separate uploader but that's a second request, and third to reload the object to get the new image/file url.

**Comment by jerel** [comment]
An ImageField shouldn't behave any different when using this adapter than when you are using DRF by itself. If you aren't uploading a file during a write operation then you should omit the field from the `attributes` dict rather than sending the url string back.

Let me know if this doesn't solve your issue.

**Comment by riklaunim** [comment]
Well, ember-data does send back what it gets for a model entry. That's the default behaviour.

In the mean time I've used bas64 based field and I've added a custom rule to do nothing if current url is posted back.
