### ISSUE TITLE
included_resources + ListSerializer

### ISSUE THREAD

**Issue by pavloo** [django-json-api/django-rest-framework-json-api#291]
Hey. I'm having problems with _included_. Here is my code:

**serializers.py**

``` python
class PatientSerializer(serializers.ModelSerializer):
    class Meta:
        model = models.Patient

class AppealSerializer(serializers.ModelSerializer):
    patient = PatientSerializer(
        read_only=True
    )

    class Meta:
        model = models.Appeal
    class JSONAPIMeta:
        included_resources = ['patient']
```

**views.py**

``` python
class AppealsListAPI(viewsets.ModelViewSet):
    serializer_class = AppealSerializer
    parser_classes = (JSONParser,)

    def get_queryset(self):
        return Appeal.objects.filter(parent=None).exclude(appeal_number='')
```

**urls.py**

``` python
url(r'^api/appeals/', views.AppealsListAPI.as_view({ 'get': 'list' }))
```

So I expect _Patient_ model be serialized and included under _included_ key as per JSON API.
But this code from **rest_framework_json_api/utils.py**:

``` python
def get_default_included_resources_from_serializer(serializer):
    try:
        return list(serializer.JSONAPIMeta.included_resources) # serializer.__class__ is ListSerializer here, and there is no JSONAPIMeta
    except AttributeError:
        return []
```

always returns an empty array (because of the reason stated in comment), hence _included_ is not populated in the resulting payload. Is there a way to overcome this issue or it's a bug? Or maybe there is something wrong with my code? Thanks.

**Comment by Humper** [comment]
I have nearly identical code and am having the same issue.

**Comment by mblayman** [comment]
I believe this is a bug. I had a similar problem and came to the same conclusion that `serializer` was a `ListSerializer` instead of the actual serializer that I wanted. DRF creates a `ListSerializer` under certain circumstances (https://github.com/tomchristie/django-rest-framework/blob/master/rest_framework/serializers.py#L121).

The *real* serializer is available at `serializer.child` on the `ListSerializer`. I hacked up my local virtualenv and changed https://github.com/django-json-api/django-rest-framework-json-api/blob/develop/rest_framework_json_api/renderers.py#L452 to reference `child` instead. Suddenly, my `included` data showed up in the results.

What is unknown to me is if the `serializer` at this line will always be a `ListSerializer` or not. I might try to put up a PR for this as I would like it fixed so I can actually side load some data. 😄

**Comment by mblayman** [comment]
Looks like @rpatterson beat me to the fix by a couple days with PR #307.

**Comment by rpatterson** [comment]
@mblayman Thanks for the nod and the heads up on this issue, I'd missed it. @pavloo @Humper Can you try out my fork/PR #307 and see if it fixes your issues?  If so, @pavloo can you close this as a duplicate?

**Comment by mblayman** [comment]
I believe this is now fixed on the develop branch. Thanks for reporting the issue.
