### ISSUE TITLE
Conform to the jsonapi.org 1.0 spec

### ISSUE THREAD

**Issue by v-bornov** [django-json-api/django-rest-framework-json-api#32]
>> When jsonapi.org reaches 1.0 this adapter plans to adopt it.

http://jsonapi.org/
2015-05-29: 1.0 final released.

**Comment by jerel** [comment]
Yes, hopefully soon.

**Comment by xxinfinityxx** [comment]
Is there any work actually done on this ? I mean would you accept PRs?

**Comment by jerel** [comment]
hey @xxinfinityxx, so `json-api` was a branch that I started back before the spec was finalized and I ended up abandoning it. I deleted it now to avoid confusion. The latest code is in the `develop` branch and any pull requests for the json-api version should be opened against it.

I'd be happy to see pull requests. At my full time gig we are using the stable version of this adapter and we have verbal authorization to build v2 of the API which will force the rewrite of this package to json api compliance. I'm happy to work with any contributors to get it started now or I'll get to do it during my 9 to 5 within the next few weeks.

For the record this will be a breaking release. We don't want to needlessly break DRF APIs but due to json-api spec's drastic changes as they reached 1.0 I figure our 2.0 release will pretty much be a rewrite.

**Comment by jsenecal** [comment]
@jerel we need this for an app I'm working during my own 9 to 5 :)

I'll see what I can do to contribute

**Comment by jsenecal** [comment]
@jerel I realized there might be a name clash with another project at https://github.com/kevin-brown/drf-json-api this project aims toward the same goal as this one but the project lacks an active maintainer...

**Comment by jerel** [comment]
@jsenecal yeah, I've been keeping an eye on that package. The current plan is to name this one `djangorestframework-jsonapi` (to align with other DRF extensions) on pypi with the import name being `rest_framework_json_api`

Also, I just pushed some initial JSON API refactoring to the `develop` branch

**Comment by jsenecal** [comment]
@jerel Ha! Well, I've been working on this as well in my fork, so I kinda wasted some time there :( - anyways let us know if/where you need help and I'll gladly help!

**Comment by bierdybard** [comment]
Thanks for your work on this, and I'm glad I found it before I went too far down the rabbit hole on my own solution.

Have you considered a design that involves a serializer which (de)serializes the Python objects directly into conformant JSON API resource objects? It makes sense to me that manipulating the fields in that matter would happen in the serializer. Perhaps a mixin would work here.

Just a thought I had as I was starting to think about implementing my own version here. As time allows I hope to also contribute some code to this effort!

**Comment by holandes22** [comment]
Hi, I've been planning to roll my own solution as well but I much rather contribute in a common  effort. I see that there are several people that are interested in this and willing to help.

Any chance you share your plans here on the repo? Making this info public and creating tickets for each tasks will allow people to contribute to the project. To start doesn't have to be too detailed, just an overview and 2 or 3 big tickets I think

**Comment by jsenecal** [comment]
So far I've been working with @jerel to implement the jsonapi spec. Go take a look at the develop branch to see where we are at.

Why don't you guys come chat with us on Gitter ?

**Comment by jerel** [comment]
This issue has been superseded by #40
