### ISSUE TITLE
Add bulk operation support

### ISSUE THREAD

**Issue by zivSher** [django-json-api/django-rest-framework-json-api#367]
Hi guys,
I'm trying to post an array of objects. (it's basically a list of dictionaries).
I'm getting 
'if data.get('type') != resource_name and request.method in ('PUT', 'POST', 'PATCH'):
AttributeError: 'list' object has no attribute 'get''

from the parsers.py.
Seems like it doesn't know to handle a case where the data is a list.
Is that functionality missing or am I doing something wrong?

I'm using 'many=true' in the serializer. 

This is the data I'm sending:
{
                "data": [
                    {
                        "type": "admin_mappings",
                        "attributes": {
                            "oxygen_id": "2222",
                            "type": "1",
                            "my_role": "manager"
                        },
                        "relationships": {
                            "container": {
                                "data": {
                                    "type": "containers",
                                    "id": "5d0554d1-22b3-441c-89f5-d6d5cdd74451"
                                }
                            }
                        }
                    },
                    {
                        "type": "admin_mappings",
                        "attributes": {
                            "oxygen_id": "3333",
                            "type": "1",
                            "my_role": "manager"
                        },
                        "relationships": {
                            "container": {
                                "data": {
                                    "type": "containers",
                                    "id": "5d0554d1-22b3-441c-89f5-d6d5cdd74451"
                                }
                            }
                        }
                    }]
}

Thanks!

**Comment by sliverc** [comment]
What you suggest is adding bulk support for json api. This is actually not part of json api standard but might still be valid to add. Best have a look at https://github.com/django-json-api/django-rest-framework-json-api/pull/393#issuecomment-353579753 for more details.

**Comment by donaldwasserman** [comment]
So this is actually something being worked on right now: https://github.com/json-api/json-api/pull/1254

I'd actually be interested in working on this, but it's not to a point yet where I've had enough time to see where it's at (the PR to the spec is still open, but I think it's mostly complete)

**Comment by puremath** [comment]
Could someone tell me what that state of this issue is and what might be the most promising path from here on? As I see it this is where we stand:

* The discussed [sideposting draft](https://github.com/json-api/json-api/pull/1197) did not make it into JSON-API [1.1RC](https://jsonapi.org/format/1.1) and seems pretty abandoned.

* There is a chance that [operations](https://github.com/json-api/json-api/pull/1254) will be included in a 1.2RC some months from now, but there is no guarantee for this to actually happen nor can it be considered a stable specification at this point.

* There is no replacement for the [bulk creation extension](https://github.com/json-api/json-api/blob/v1.0/extensions/bulk/index.md) in the [new extension model](https://jsonapi.org/extensions/) and there might never be since the above mentioned operations are worked on.

Are we pretty much stuck on this or is there a promising approach at this moment?

**Comment by sliverc** [comment]
As Django JSON API our goal is to implement the JSON API specification so I guess this question is better to be answered there.

What you can do is implement the old bulk creation extensions as described here https://github.com/django-json-api/django-rest-framework-json-api/pull/393#issuecomment-353579753 in your code base. But this will be custom and client code will need to be custom as well.

**Comment by sliverc** [comment]
Closing this issue as this is better discussed in json api specification. So if you feel like this feature is needed join the discussion there as outlined in https://github.com/django-json-api/django-rest-framework-json-api/issues/367#issuecomment-472327971 or use the workaround https://github.com/django-json-api/django-rest-framework-json-api/pull/393#issuecomment-353579753
