### ISSUE TITLE
release 2.3.0?

### ISSUE THREAD

**Issue by noslouch** [django-json-api/django-rest-framework-json-api#382]
It's in the changelog but it hasn't been released. Would you mind cutting a release for pypi? In particular the `Added nested included serializer support for remapped relations` is something we need.

**Comment by sliverc** [comment]
I agree it would be great to have a new release. But I think at least PR https://github.com/django-json-api/django-rest-framework-json-api/pull/376 needs to be merged as otherwise backwards compatibility is broken.

Also ideal would be to merge https://github.com/django-json-api/django-rest-framework-json-api/pull/374 as well.

**Comment by mblayman** [comment]
I just merged #376. I've not done a release for DJA before, but I now have the upload permissions. When I have some time, I'll try to put out a release.

**Comment by noslouch** [comment]
thanks!

**Comment by mblayman** [comment]
I pushed the release to PyPI. Enjoy! 😄
