### ISSUE TITLE
SparseFieldsetsMixin catches invalid key from URL

### ISSUE THREAD

**Issue by tokwiat** [django-json-api/django-rest-framework-json-api#519]
Hi,

Once I want to use sparse fields in URL eg.:

`/api/something/?fields[bar]=somefield`

The SparseFieldsetsMixin is checking for the key as substring:

`key for key in request.query_params if sparse_fieldset_query_param in key`

That causes the situation where not only 'fields[bar]' matches the if case but also prefixes:

`/api/something/?someotherchars_fields[bar]=somefield`

or 

`/api/something/?foooooooofields[bar]=somefield`

Such behavior can cause some unexpected situations once for instance other mixin will use 'fields' key in some way to perform other operations on the same endpoint.

**Comment by sliverc** [comment]
This is odd. When looking at the code I do not really see why there is a `in` and not simply getting the field directly from the query params. Not quiet sure why this has been done this way. Any ideas?

Anyhow I do not think this is a critical issue though as a query parameter `foooooooofields` is not a valid json api query param. See [QueryParameterValidationFilter](https://django-rest-framework-json-api.readthedocs.io/en/stable/usage.html#queryparametervalidationfilter) for more details. Basically additional filter query params should be defined as [`filter[nameoffilter]`](https://jsonapi.org/format/#fetching-filtering).

This said a PR would still be welcome.

**Comment by tokwiat** [comment]
> Anyhow I do not think this is a critical issue though as a query parameter foooooooofields is not a valid json api query param. See QueryParameterValidationFilter for more details. Basically additional filter query params should be defined as filter[nameoffilter].

That's correct, sorry, I didn't mentioned the version I use, which is apparently quite old (2.2.0) and QueryParameterValidationFilter is not present there. So considering latest version `foooooooofields` would not be allowed anyway.

> This is odd. When looking at the code I do not really see why there is a in and not simply getting the field directly from the query params. Not quiet sure why this has been done this way. Any ideas?

Still I would also like to know the reason using 'in' keyword in this case.

Thanks!

**Comment by sliverc** [comment]
The feature has been implemented in https://github.com/django-json-api/django-rest-framework-json-api/pull/108 and hasn't really changed much since.

@jsenecal 
This has been way back when `SparseFieldsetsMixin` has been implemented so maybe you won't remember... but if you do could you give some more insight why [key in](https://github.com/django-json-api/django-rest-framework-json-api/blob/master/rest_framework_json_api/serializers.py#L69) approach has been chosen instead of a simple `request.query_params.get(sparse_fieldset_query_param)`? Maybe its simply a bug but it is rather a complex construct to just happen like that :wink:.
