### ISSUE TITLE
Do `select_related` for ?include

### ISSUE THREAD

**Issue by Anton-Shutik** [django-json-api/django-rest-framework-json-api#591]
I've found that we have nice `prefetch_for_includes` option on the ModelViewSet. 
I would also like `select_for_includes` mixin that will call add `select_related` and pass there values accordingly to the mapping. 
If you like the idea I'll create PR for that

**Comment by Anton-Shutik** [comment]
We can have a separate Mixin for that or just add the logic to exiting one. 

```python
class SelectForIncludesMixin(object):

    def get_queryset(self):
        """
        This viewset provides a helper attribute to select related models
        based on the include specified in the URL.

        __all__ can be used to specify a select which should be done regardless of the include

        .. code:: python

            # When MyViewSet is called with ?include=author it will prefetch author and authorbio
            class MyViewSet(viewsets.ModelViewSet):
                queryset = Book.objects.all()
                select_for_includes = {
                    '__all__': [],
                    'author': ['author', 'author__authorbio'],
                    'category.section': ['category']
                }
        """
        qs = super(PrefetchForIncludesHelperMixin, self).get_queryset()
        if not hasattr(self, 'select_for_includes'):
            return qs

        includes = self.request.GET.get('include', '').split(',')
        for inc in includes + ['__all__']:
            selects = self.select_for_includes.get(inc)
            if selects:
                qs = qs.select_related(*selects)

        return qs
```

**Comment by Anton-Shutik** [comment]
@sliverc What do you think about it ?

**Comment by sliverc** [comment]
In corner cases it might be helpful to have a SelectForIncludesMixin but a user should not get into the habit of using `select_for_includes` for normal cases so if we add such a mixin it should come with a fixed AutoPrefetchMixin which also automatically selects `select_related`.

I think having one mixin for select/prefetch for includes and one for auto prefetching would be a good idea. 

I guess we need to think about renaming the mixins (deprecating old name) as it might be confusing otherwise. Suggestions are welcome.

Related to #337

**Comment by Anton-Shutik** [comment]
@sliverc I've created [PR](https://github.com/django-json-api/django-rest-framework-json-api/pull/600) for that. Would you mind taking a look ?
Thanks
