### ISSUE TITLE
filter on uuid seems to break

### ISSUE THREAD

**Issue by dbinetti** [django-json-api/django-rest-framework-json-api#696]
When trying to filter on a UUID field (not as PK, but as a normal field) it does not return any results.  looking at the JSONAPI formatted return, it says 
<img width="1204" alt="Screen Shot 2019-08-24 at 16 46 12" src="https://user-images.githubusercontent.com/161722/63643860-95f51280-c68f-11e9-96e4-c967df9cd7a8.png">

but it is a properly formatted UUID.  

```
{
"errors": [
{
"detail": "invalid query parameter: format",
"source": {
"pointer": "/data"
},
"status": "400"
}
]
}
```

If I submit an improperly formatted UUID it returns   
<img width="1204" alt="Screen Shot 2019-08-24 at 16 50 51" src="https://user-images.githubusercontent.com/161722/63643867-bb821c00-c68f-11e9-842c-425454326e56.png">

With `group_id` being the UUID I'm trying to filter by.    And the JSONAPI formatted response is the same.  Seems like a bug -- but am I doing something wrong?

**Comment by dbinetti** [comment]
Sorry, submitted string is:
http://localhost:8000/registration/entry?filter%5Bgroup_id%5D=cf4f0d51ad4e45b6ab99e118e99e04

**Comment by n2ygk** [comment]
@dbinetti My guess is that it says "invalid **query parameter**: format" likely because you are using the browsable API and it is tacking on a `&format=api` query parameter. This use of **format** as a query parameter is a DRF feature (both an `Accept:` header or a `?format=` query parameter are both supported). If you are using the [QueryParameterValidationFilter](https://django-rest-framework-json-api.readthedocs.io/en/stable/usage.html#queryparametervalidationfilter) which does not include `format` as a valid query parameter.  Although I was unable to reproduce....

If my guess is correct, then his is probably something we should document and/or allow in QueryParameterValidationFilter (even though it's not a valid JSON:API query parameter).

Try using Postman, curl, or wget to do a GET of `http://localhost:8000/registration/entry?filter%5Bgroup_id%5D=cf4f0d51ad4e45b6ab99e118e99e04` and let us know.

**Comment by n2ygk** [comment]
I was able to reproduce this with the browsable API.  It has a default mode that just sets the Accept header but if you click on the down-arrow under GET and select either of the two choices, then a `format` query parameter is added to the request and is rejected by QueryParameterValidationFilter.
<img width="925" alt="Screen Shot 2019-08-24 at 9 25 45 PM" src="https://user-images.githubusercontent.com/4356471/63644370-e67f6680-c6b5-11e9-8cbd-4ca6ce0a4a3e.png">

<img width="925" alt="Screen Shot 2019-08-24 at 9 26 12 PM" src="https://user-images.githubusercontent.com/4356471/63644369-d8314a80-c6b5-11e9-909e-f0b530988a6f.png">

This isn't to say you still may be having a problem with the UUID matching, but the "invalid query parameter: format" error is a red herring.

**Comment by dbinetti** [comment]
I’ll close this since my issue is resolved, but I think what I would have expectged here was a “no results” or 404 right?
