### ISSUE TITLE
Allow overwriting of get_serializer_class with related urls

### ISSUE THREAD

**Issue by uliSchuster** [django-json-api/django-rest-framework-json-api#859]
In https://github.com/django-json-api/django-rest-framework-json-api/blob/a67a521327c9ec62a18a875abf13504a72d8eaf0/rest_framework_json_api/views.py#L182
the serializer class defined in the view is used directly. This is a problem if one wants to override `get_serializer_class()`; e.g., to provide a different serializer depending on the view action. Is there a reason to prevent dynamic serializer selection here via `get_serializer_class()`?

**Comment by sliverc** [comment]
This issue only seems to relate to [related urls](https://django-rest-framework-json-api.readthedocs.io/en/stable/usage.html#related-urls) which need to be specially configured to enable. Otherwise it should not be a problem to overwrite `get_serializer_class` in any other case.

I think the issue is that `RelatedMixin` already overwrites `get_serializer_class` so `serializer_class` needs to be accessed here. It should be possible to rename `RelatedMixin.get_serializer_class` method to `get_related_serializer_class` and it should work (emphasis on should... :smile:).

PR is welcome.

**Comment by uliSchuster** [comment]
If I understand you correctly, the actual bug is that `RelatedMixin` overwrites `get_serializer_class()` in the first place - this might already lead to unintended consequences for upstream users of a view that uses the mixin. Instead, the method should be called `get_related_serializer_class()`, because it does exactly what the name implies. It then would not shadow the actual `get_serializer_class()` method, which would continue to return the serializer class of the view proper, instead of serializerss for related views. Is this understanding correct?
Then, a fix might lead to some upstream user code to break that is already designed around the bug.
But yes, I will try to fix the issue and provide a PR.

**Comment by uliSchuster** [comment]
[Here](https://github.com/uliSchuster/django-rest-framework-json-api/tree/859-fix-attempt) is my attempted fix along the lines outlined above. Unfortunately, it does not seem to work, as it breaks two assertions in `test_views.py::TestRelatedMixin::test_retrieve_related_single` and `test_views.py::TestRelatedMixin::test_retrieve_related_single_reverse_lookup`
To separate related serializers from parent serializers, I also created a `get_related_serializer()` method. But this does not seem to be sufficient. By now, I am running out of ideas...

**Comment by uliSchuster** [comment]
After some more debugging, I didn't get any further unfortunately. It seems that `retrieve_related` returns the correct response - at least, it includes the correct serialized data. But then during response rendering, something goes wrong and the   resource type get marked as being the parent resource instead of the related resource.

**Comment by sliverc** [comment]
> this might already lead to unintended consequences for upstream users of a view that uses the mixin.

To clarify, this particular issue only affects users who use related urls. Such are not on by default but need to be activated through a specific url pattern as outlined in the [documentation](https://django-rest-framework-json-api.readthedocs.io/en/stable/usage.html#related-urls). Without those urls this [if statement](https://github.com/django-json-api/django-rest-framework-json-api/blob/master/rest_framework_json_api/views.py#L153) won't be true and the `get_serializer_class` method simply calls super, as it would if it were not there.

I haven't analyzed the issue fully but I assume the issue lies [here](https://github.com/django-json-api/django-rest-framework-json-api/blob/master/rest_framework_json_api/utils.py#L55) where the resource name is determined. Most likely does it need a similar if as [here](https://github.com/django-json-api/django-rest-framework-json-api/blob/master/rest_framework_json_api/views.py#L153) to determine whether it needs to get `serializer_class` from `get_serializer_class` or `get_related_serializer_class`.

**Comment by uliSchuster** [comment]
Thanks for this additional hint. Your assumption seems to be right. I added an if-statement to determine if the resource name of the related resource is needed or the parent resource. I extended the Author view in the example to test the issue - made sure that it fails on master first, then add my changes and see that the tests pass.

This is where another issue now pops up, in OpenAPI generation: `test_path_without_parameters` and `test_path_with_id_parameter` fail. I am somewhat reluctant to dig into all the OpenAPI code - do you have another hint for me were to look?

**Comment by sliverc** [comment]
I do not quite see how such a change makes those tests fail. If you don't find the issue feel free to create a PR with what you got.

**Comment by uliSchuster** [comment]
The problem seems to be in the snapshot tests, where the expected response does not match anymore. Instead of
```json
                "items": {
                  "$ref": "#/components/schemas/Author"
                },
```
we now get
```json
                "items": {
                  "$ref": "#/components/schemas/AuthorList"
                },
```
I suppose the new expected result is correct, but I can't tell for sure because I am not familiar with the OpenAPI schema generation.

I will open a PR of my changes, so you can judge for yourself. Thanks for your help!

**Comment by n2ygk** [comment]
See my review comments.
