### ISSUE TITLE
Endpoint does not support the include parameter

### ISSUE THREAD

**Issue by ro70** [django-json-api/django-rest-framework-json-api#873]
I'm not sure where the problem is (ResourceRelatedField?). When I'm requesting
```
/as?include=bs
```
I get the error message
```
This endpoint does not support the include parameter for path bs
```
My models and serializers roughly look like these:
```
class A(models.Model):
   ...

class B(models.Model):
   a = models.ForeignKey(
      'A',
      on_delete=models.CASCADE,
      related_name='bs',
   )

class BSerializer(serializers.ModelSerializer):
   class Meta:
      model = B
      fields = '__all__'

class ASerializer(serializers.ModelSerializer):
   included_serializers = {
      'bs': BSerializer,
   }

   bs = relations.ResourceRelatedField(
      many=True,
      read_only=True,
   )

   class Meta:
      model = A
      fields = '__all__'
```
I'm using dja version 3.2.0 (updating to 4.0.0 didn't solve the issue).

**Comment by sliverc** [comment]
In this simplified example it all looks good to me and should work. I assume the error might have been removed due to the simplification (e.g. inflection happens here which might have caused it or something similar). 

The exception which is raised happens [here](https://github.com/django-json-api/django-rest-framework-json-api/blob/master/rest_framework_json_api/serializers.py#L116). What you could do with pdb is to debug through this code bit to see what happens in your actual code. Maybe this will shed some light on the issue. Another way to make it clearer would be to create a PR with a reproducing test.

**Comment by ro70** [comment]
I found the problem. The line
```
this_field_name = inflection.underscore(field_path[0])
```
https://github.com/django-json-api/django-rest-framework-json-api/blob/master/rest_framework_json_api/serializers.py#L113 

changes our camelcase include parameter to an underscore one. We have to adjust this in our code. The example above doesn't show this problem.

@sliverc Oh, you commented the issue right now too ;) Thank you, I'm closing this...
