### ISSUE TITLE
Filtering related fields with related_field

### ISSUE THREAD

**Issue by SafaAlfulaij** [django-json-api/django-rest-framework-json-api#905]
How can we filter the related fields `/authors/1/entries/`?

**Comment by SafaAlfulaij** [comment]
I took some time and now I have a solid thinking that we have to use the related views for related fields.
So, for the above exmaple, it should use a special function of `EntryViewSet` instead of `AuthorViewSet`'s `related_fields` function.
Why?
1. The actual resource we are fetching here is the related resource. It makes more sense to have it's viewset serve the request.
2. We get all querysets, filtering, ordering, pagination, permissions for free (almost, after some modifications).
3. The "parent" resource (author in the example above) is just needed for authentication, and as a reference for related fields.

Currently what I do is this (not optimal and performant, but does the job):
1. Have the related field viewset handle the relation through `as_view`, passing the `list` for -to-many and `retrieve` for single objects.
2. Pass in the kwargs of `re_path` the parent view class, and whatever else needed for filtering.
3. In `get_queryset`, I check if the parent viewset is defined in kwargs, create the viewset, passing proper pk from url arguments, and some other fields, then I do `get_object` to check permissions, and save the instance for future use if any (could be for making performant queries by select_related the field in the parent request and returning it directly.

This approach has things to consider:
1. Client must pass the resulting queryset in `get_queryset` to a parent function to execute filtering for relations.
2. Performance of creating a viewset for each related fetch can be a lot.
3. Clients should use another mixin for the relations if the relation resource shouldn't be listed. For example, entry `flags` shouldn't accept `GET /entry-flags` api, but should accept `GET /entry/1/flags`.

I'll see if I can clean up the code and have others opinion.

**Comment by sliverc** [comment]
related urls served by a single viewset is a simple way of adding relationships links. It has its limitation though such as no filter support. Also important to note is that this got added later. The idea was to simplify the process of providing relationships links.

Before [RelationshipView](https://django-rest-framework-json-api.readthedocs.io/en/stable/usage.html#relationshipview) was actually used for related urls and can still be used today. So if you wanna use filters better switch to `RelationshipView` instead of related urls by a single view set. More configuration is needed but gives you the full power of DRF.

With all the complexity and errors related urls served by a single viewset brought I wondered though whether it was a good idea to include this feature. Or maybe there is a better way of simplifying support of related urls then a need to configure each single relationship individuall per resources as currently done with `RelationshipView`.
